source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

pod 'PKRevealController'
pod 'JSQMessagesViewController'
pod 'CZPicker'
pod "RAReorderableLayout"
pod "Alamofire"
pod 'AZDropdownMenu'
pod 'AMPopTip'
pod 'DropDown'
pod 'Eureka', '~> 1.7'
pod 'SwiftyJSON'